apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: ingres
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: ingres
  rules:
  - http:
      paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service:
              name: client-service-clusterip
              port:
                number: 3000
            
        - path: /api/?(.*)
          pathType: Prefix
          backend:
            service:
              name: server-service-clusterip
              port:
                number: 5000