apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-local

spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/k8spv-project"
    type: DirectoryOrCreate